name: Twitter Autobot

on:
  schedule:
    # Run every day at 2:30 AM UTC (8:00 AM IST)
    - cron: "30 2 * * *"
  workflow_dispatch:
    inputs:
      mode:
        description: "Select mode (scheduled/immediate)"
        required: true
        default: "scheduled"
        type: choice
        options:
          - scheduled
          - immediate

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 900 # 15 hours to ensure full coverage

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Twitter bot
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TARGET_USERNAMES: ${{ secrets.TARGET_USERNAMES }}
          TZ: "Asia/Kolkata" # Set timezone to IST
        run: |
          if [ "${{ inputs.mode }}" = "immediate" ]; then
            echo "Starting immediate posting mode (5 tweets with 5-minute gaps)"
            python -c "from schedule_tweets import post_immediate_tweets; from auth import authenticate; post_immediate_tweets(authenticate())"
          else
            echo "Starting regular scheduled mode (15 tweets between 8AM-10PM IST)"
            # Run with explicit timezone setting
            TZ='Asia/Kolkata' python main.py
          fi
