name: Twitter Autobot

on:
  schedule:
    - cron: "50 7 * * *" # Main daily schedule (7:50 AM UTC)
  workflow_dispatch:
    inputs:
      mode:
        description: "Select mode (scheduled/immediate)"
        required: true
        default: "scheduled"
        type: choice
        options:
          - scheduled
          - immediate

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 840 # 14 hours for scheduled mode

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Twitter bot
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          if [ "${{ inputs.mode }}" = "immediate" ]; then
            echo "Starting immediate posting mode (5 tweets with 2-minute gaps)"
            for i in {1..5}; do
              python -c "from schedule_tweets import post_random_tweet; from auth import authenticate; client = authenticate(); post_random_tweet(client)"
              if [ $i -ne 5 ]; then
                sleep 120
              fi
            done
          else
            echo "Starting regular scheduled mode"
            python main.py
          fi
